on: [pull_request]
name: Benchmark

defaults:
  run:
    shell: bash

jobs:
  bench:
    name: Bench library
    runs-on: ubuntu-20.04-16-cores
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo -qq apt-get -y update
          sudo -qq apt-get -y install protobuf-compiler libprotobuf-dev
          cargo install --quiet critcmp

      - name: Checkout baseline sources
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Benchmark baseline
        run: cargo bench --quiet --package surrealdb --no-default-features --features kv-mem

      - name: Checkout PR sources
        uses: actions/checkout@v3

      - name: Benchmark PR
        run: cargo bench --quiet --package surrealdb --no-default-features --features kv-mem

      
#      - name: Copy benchmark results to artifacts directory
#        run: |
#          mkdir -p artifacts
#          cat > artifacts/message.md <<EOF
#          # Test Message
          
#      - name: Save PR message as artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: pr_message
#          path: artifacts
